// <auto-generated />
namespace OurTunes.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FrontEndTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FrontEndTest));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111810239_Front-End-Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
